### ISSUE TITLE
Test suite failure: Your dummy space has been corrupted. Size is: ""

### ISSUE THREAD

**Issue by peti** [fpco/executable-hash#1]
A complete build log is at http://hydra.cryp.to/build/626545/log/raw.

**Comment by mgsloan** [comment]
Thanks for the report!  This is a mystery to me - I can't reproduce the problem locally.  I'm using an identical set of dependencies.

Here's where the dummy string is generated: https://github.com/fpco/executable-hash/blob/master/System/Executable/Hash/Internal.hs#L20

And here's where the exception is coming from: https://github.com/snoyberg/file-embed/blob/master/Data/FileEmbed.hs#L238

 Is `feexecutable-hash` a substring of the binary?  While I'm not sure if it would be helpful, maybe you could upload the `dist/test-inject/test-inject` binary?

Perhaps it's something nix related?  I know that nix tries very hard to make builds deterministic, but I can't see that breaking this..

**Comment by peti** [comment]
The binaries are available in https://gist.github.com/peti/ae4fdd4e75171cd449a1. I hope this helps.

**Comment by mgsloan** [comment]
Ah, that is helpful, thanks!  Your binaries are tiny compared to mine, likely because they are dynamically linked.  Since the dummy string is in the library, it isn't found within the executable's binary.

The API should probably be changed to make this a nonissue.  This would involve the following changes:
- Make `executableHash` and `injectedExecutableHash` into TH functions, which yield `Q Exp`.
- Have `file-embed` replace multiple instances of the dummy string.  This way multiple usages of `executable-hash` will still work.  This is one of the reasons I didn't do this in the first place.

The alternative would be to demand statically linked binaries, but since that's avoidable, this seems like a good thing to change.

**Comment by mgsloan** [comment]
I think I prefer this anyway, because it'll make it clearer that the `executableHash` function is doing something magical.

**Comment by mgsloan** [comment]
@peti I've uploaded `executable-hash-0.2.0.0` to hackage.  Can you please verify that this resolves the issue?

**Comment by peti** [comment]
I'm a little late with my response. I'm sorry about that. New versions of the package work fine in NIxOS: http://hydra.nixos.org/job/nixpkgs/haskell-updates/haskellngPackages.executable-hash.x86_64-linux.

**Comment by mgsloan** [comment]
No worries, thanks for verifying!
